package com.dttr.tchat.entities;
// Generated Jan 28, 2019 12:43:14 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message")
public class Message implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer messid;
	@JsonIgnore
	private Chat chat;
	@JsonIgnore
	private Userinfo userinfo;
	private String content;
	private Date sendtime;
	@JsonIgnore
	private Set<UserHasMessage> userHasMessages = new HashSet<UserHasMessage>(0);

	public Message() {
	}

	public Message(Chat chat, Userinfo userinfo, String content, Date sendtime, Set<UserHasMessage> userHasMessages) {
		this.chat = chat;
		this.userinfo = userinfo;
		this.content = content;
		this.sendtime = sendtime;
		this.userHasMessages = userHasMessages;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "messid", unique = true, nullable = false)
	public Integer getMessid() {
		return this.messid;
	}

	public void setMessid(Integer messid) {
		this.messid = messid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chatid")
	public Chat getChat() {
		return this.chat;
	}

	public void setChat(Chat chat) {
		this.chat = chat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sender")
	public Userinfo getUserinfo() {
		return this.userinfo;
	}

	public void setUserinfo(Userinfo userinfo) {
		this.userinfo = userinfo;
	}

	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "sendtime", length = 19)
	public Date getSendtime() {
		return this.sendtime;
	}

	public void setSendtime(Date sendtime) {
		this.sendtime = sendtime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "message",orphanRemoval=true)
	public Set<UserHasMessage> getUserHasMessages() {
		return this.userHasMessages;
	}

	public void setUserHasMessages(Set<UserHasMessage> userHasMessages) {
		this.userHasMessages = userHasMessages;
	}

}
