package com.dttr.tchat.entities;
// Generated Jan 28, 2019 12:43:14 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserHasChat generated by hbm2java
 */
@Entity
@Table(name = "user_has_chat")
public class UserHasChat implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private UserHasChatId id;
	private Chat chat;
	private Userinfo userinfo;

	public UserHasChat() {
	}

	public UserHasChat(UserHasChatId id, Chat chat, Userinfo userinfo) {
		this.id = id;
		this.chat = chat;
		this.userinfo = userinfo;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userid", column = @Column(name = "userid", nullable = false)),
			@AttributeOverride(name = "chatid", column = @Column(name = "chatid", nullable = false)) })
	public UserHasChatId getId() {
		return this.id;
	}

	public void setId(UserHasChatId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chatid", nullable = false, insertable = false, updatable = false)
	public Chat getChat() {
		return this.chat;
	}

	public void setChat(Chat chat) {
		this.chat = chat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid", nullable = false, insertable = false, updatable = false)
	public Userinfo getUserinfo() {
		return this.userinfo;
	}

	public void setUserinfo(Userinfo userinfo) {
		this.userinfo = userinfo;
	}

}
