package com.dttr.tchat.entities;
// Generated Jan 28, 2019 12:43:14 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserHasChatId generated by hbm2java
 */
@Embeddable
public class UserHasChatId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int userid;
	private int chatid;

	public UserHasChatId() {
	}

	public UserHasChatId(int userid, int chatid) {
		this.userid = userid;
		this.chatid = chatid;
	}

	@Column(name = "userid", nullable = false)
	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	@Column(name = "chatid", nullable = false)
	public int getChatid() {
		return this.chatid;
	}

	public void setChatid(int chatid) {
		this.chatid = chatid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserHasChatId))
			return false;
		UserHasChatId castOther = (UserHasChatId) other;

		return (this.getUserid() == castOther.getUserid()) && (this.getChatid() == castOther.getChatid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserid();
		result = 37 * result + this.getChatid();
		return result;
	}

}
